version: '3.8'

services:
  clickhouse-telemetry:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: my_database
      CLICKHOUSE_USER: username
      CLICKHOUSE_PASSWORD: password
    ports:
      - "18123:8123"
    restart: always